name: docum
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hidden_drawer_menu: ^3.0.1
  syncfusion_flutter_signaturepad: ^21.1.41
  get:
  docx_template: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
   - assets/
 

